const questions = [

  { id: 1, text: "I dream of being so good at what I do that my expert advice will be sought continually", category: "TF" },
  { id: 2, text: "I am most fulfilled in my work when I have been able to integrate and manage the efforts of others", category: "GM" },
  { id: 3, text: "I dream of having a career that will allow me the freedom to do a job my own way and on my own schedule", category: "AU" },
  { id: 4, text: "Security and stability are more important to me than freedom and autonomy", category: "SE" },
  { id: 5, text: "I am always on the lookout for ideas that would permit me to start my own enterprise", category: "EC" },
  { id: 6, text: "I will feel successful in my career only if I have a feeling of having made a real contribution to the welfare of society", category: "SV" },
  { id: 7, text: "I dream of a career in which I can solve problems or win out in situations that are extremely challenging", category: "CH" },
  { id: 8, text: "I would rather leave my organization than to be put in a job that would compromise my ability to pursue personal and family concerns", category: "LS" },
  { id: 9, text: "I will feel successful in my career only if I can develop technical or functional skills to a very high level competence", category: "TF" },
  { id: 10, text: "I dream of being in charge of a complex organization and making decisions that affect many people", category: "GM" },
  { id: 11, text: "I am most fulfilled in my work when I am completely free to define my own tasks, schedules and procedures", category: "AU" },
  { id: 12, text: "I would rather leave my organization altogether than accept an assignment that would jeopardize my security in that organization", category: "SE" },
  { id: 13, text: "Building my own business is more important to me than achieving a high-level managerial position in someone else’s organization", category: "EC" },
  { id: 14, text: "I am most fulfilled in my career when I have been able to use my talents in the service of others", category: "SV" },
  { id: 15, text: "I will feel successful in my career only if I face and overcome very difficult challenges", category: "CH" },
  { id: 16, text: "I dream of a career that will permit me to integrate my personal, family, and work needs", category: "LS" },
  { id: 17, text: "Becoming a senior functional manager in my area of expertise is more attractive to me than becoming a general manager", category: "TF" },
  { id: 18, text: "I will feel successful in my career only if I become a general manager in some organization", category: "GM" },
  { id: 19, text: "I will feel successful in my career only if I achieve complete autonomy and freedom", category: "AU" },
  { id: 20, text: "I seek jobs in organizations that will give me a sense of security and stability", category: "SE" },
  { id: 21, text: "I am most fulfilled in my career when I have been able to build something that is entirely the result of my own ideas and efforts", category: "EC" },
  { id: 22, text: "Using my skills to make the world a better place to live and work is more important to me than achieving a high-level managerial position.", category: "SV" },
  { id: 23, text: "I have been most fulfilled in my career when I have solved seemingly unsolvable problems or won out over seemingly impossible odds", category: "CH" },
  { id: 24, text: "I feel successful in life only if I have been able to balance my personal, family, and career requirements", category: "LS" },
  { id: 25, text: "I would rather leave my organization than accept a rotational assignment that would take me out of my area of expertise", category: "TF" },
  { id: 26, text: "Becoming a general manager is more attractive to me than becoming a senior functional manager in my current area of expertise", category: "GM" },
  { id: 27, text: "The chance to do a job my own way, free of rules and constraints, is more important to me than security", category: "AU" },
  { id: 28, text: "I am most fulfilled in my work when I feel that I have complete financial and employment security", category: "SE" },
  { id: 29, text: "I will feel successful in my career only if I succeed in creating or building something that is entirely my own product or idea", category: "EC" },
  { id: 30, text: "I dream of having a career that makes a real contribution to humanity and society", category: "SV" },
  { id: 31, text: "I seek out work opportunities that strongly challenge my problem solving and/or competitive skills", category: "CH" },
  { id: 32, text: "Balancing the demands of personal and professional life is more important to me than achieving a high-level managerial position", category: "LS" },
  { id: 33, text: "I am most fulfilled in my work when I have been able to use my special skills and talents", category: "TF" },
  { id: 34, text: "I would rather leave my organization than accept a job that would take me away from the general managerial track", category: "GM" },
  { id: 35, text: "I would rather leave my organization than accept a job that would reduce my autonomy and freedom", category: "AU" },
  { id: 36, text: "I dream of having a career that will allow me to feel a sense of security and stability", category: "SE" },
  { id: 37, text: "I dream of starting up and building my own business", category: "EC" },
  { id: 38, text: "I would rather leave my organization than accept an assignment that would undermine my ability to be of service to others", category: "SV" },
  { id: 39, text: "Working on problems that are almost unsolvable is more important to me than achieving a high-level managerial position", category: "CH" },
  { id: 40, text: "I have always sought out work opportunities that minimize interference with personal or family concerns", category: "LS" },
    ];
  
  export default questions;
  